package com.artqiyi.dahuashai.game.mapper;

import org.apache.ibatis.annotations.Param;

import com.artqiyi.dahuashai.game.domain.GameConfig;
import com.artqiyi.dahuashai.game.domain.GameConfigExample;

import java.util.List;

public interface GameConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_config
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    long countByExample(GameConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_config
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int deleteByExample(GameConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_config
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_config
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int insert(GameConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_config
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int insertSelective(GameConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_config
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    List<GameConfig> selectByExample(GameConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_config
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    GameConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_config
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") GameConfig record, @Param("example") GameConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_config
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int updateByExample(@Param("record") GameConfig record, @Param("example") GameConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_config
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int updateByPrimaryKeySelective(GameConfig entity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_config
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    int updateByPrimaryKey(GameConfig entity);
}