package com.artqiyi.dahuashai.game.domain;

import java.util.Date;

public class GameRankRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rank_record.id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rank_record.game_model_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Long gameModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rank_record.game_model_key
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String gameModelKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rank_record.user_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rank_record.user_nickname
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String userNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rank_record.score
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_rank_record.create_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rank_record.id
     *
     * @return the value of game_rank_record.id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rank_record.id
     *
     * @param id the value for game_rank_record.id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rank_record.game_model_id
     *
     * @return the value of game_rank_record.game_model_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Long getGameModelId() {
        return gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rank_record.game_model_id
     *
     * @param gameModelId the value for game_rank_record.game_model_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setGameModelId(Long gameModelId) {
        this.gameModelId = gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rank_record.game_model_key
     *
     * @return the value of game_rank_record.game_model_key
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getGameModelKey() {
        return gameModelKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rank_record.game_model_key
     *
     * @param gameModelKey the value for game_rank_record.game_model_key
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setGameModelKey(String gameModelKey) {
        this.gameModelKey = gameModelKey == null ? null : gameModelKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rank_record.user_id
     *
     * @return the value of game_rank_record.user_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rank_record.user_id
     *
     * @param userId the value for game_rank_record.user_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rank_record.user_nickname
     *
     * @return the value of game_rank_record.user_nickname
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rank_record.user_nickname
     *
     * @param userNickname the value for game_rank_record.user_nickname
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rank_record.score
     *
     * @return the value of game_rank_record.score
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rank_record.score
     *
     * @param score the value for game_rank_record.score
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_rank_record.create_time
     *
     * @return the value of game_rank_record.create_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_rank_record.create_time
     *
     * @param createTime the value for game_rank_record.create_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}