package com.artqiyi.dahuashai.game.domain;

import java.util.Date;

public class GameModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.game_model_key
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String gameModelKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.game_model_name
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String gameModelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.icon_url
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String iconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.bg_img
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String bgImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.icon_url_x
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String iconUrlX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.bg_img_x
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String bgImgX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.sort
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Short sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.status
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.deleted
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.remark
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.extentStr1
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String extentstr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.extentStr2
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String extentstr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.create_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.create_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.updator_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Long updatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_model.update_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.id
     *
     * @return the value of game_model.id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.id
     *
     * @param id the value for game_model.id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.game_model_key
     *
     * @return the value of game_model.game_model_key
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getGameModelKey() {
        return gameModelKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.game_model_key
     *
     * @param gameModelKey the value for game_model.game_model_key
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setGameModelKey(String gameModelKey) {
        this.gameModelKey = gameModelKey == null ? null : gameModelKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.game_model_name
     *
     * @return the value of game_model.game_model_name
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getGameModelName() {
        return gameModelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.game_model_name
     *
     * @param gameModelName the value for game_model.game_model_name
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setGameModelName(String gameModelName) {
        this.gameModelName = gameModelName == null ? null : gameModelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.icon_url
     *
     * @return the value of game_model.icon_url
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.icon_url
     *
     * @param iconUrl the value for game_model.icon_url
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.bg_img
     *
     * @return the value of game_model.bg_img
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getBgImg() {
        return bgImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.bg_img
     *
     * @param bgImg the value for game_model.bg_img
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setBgImg(String bgImg) {
        this.bgImg = bgImg == null ? null : bgImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.icon_url_x
     *
     * @return the value of game_model.icon_url_x
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getIconUrlX() {
        return iconUrlX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.icon_url_x
     *
     * @param iconUrlX the value for game_model.icon_url_x
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setIconUrlX(String iconUrlX) {
        this.iconUrlX = iconUrlX == null ? null : iconUrlX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.bg_img_x
     *
     * @return the value of game_model.bg_img_x
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getBgImgX() {
        return bgImgX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.bg_img_x
     *
     * @param bgImgX the value for game_model.bg_img_x
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setBgImgX(String bgImgX) {
        this.bgImgX = bgImgX == null ? null : bgImgX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.sort
     *
     * @return the value of game_model.sort
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.sort
     *
     * @param sort the value for game_model.sort
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.status
     *
     * @return the value of game_model.status
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.status
     *
     * @param status the value for game_model.status
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.deleted
     *
     * @return the value of game_model.deleted
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.deleted
     *
     * @param deleted the value for game_model.deleted
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.remark
     *
     * @return the value of game_model.remark
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.remark
     *
     * @param remark the value for game_model.remark
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.extentStr1
     *
     * @return the value of game_model.extentStr1
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getExtentstr1() {
        return extentstr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.extentStr1
     *
     * @param extentstr1 the value for game_model.extentStr1
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setExtentstr1(String extentstr1) {
        this.extentstr1 = extentstr1 == null ? null : extentstr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.extentStr2
     *
     * @return the value of game_model.extentStr2
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getExtentstr2() {
        return extentstr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.extentStr2
     *
     * @param extentstr2 the value for game_model.extentStr2
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setExtentstr2(String extentstr2) {
        this.extentstr2 = extentstr2 == null ? null : extentstr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.create_id
     *
     * @return the value of game_model.create_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.create_id
     *
     * @param createId the value for game_model.create_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.create_time
     *
     * @return the value of game_model.create_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.create_time
     *
     * @param createTime the value for game_model.create_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.updator_id
     *
     * @return the value of game_model.updator_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Long getUpdatorId() {
        return updatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.updator_id
     *
     * @param updatorId the value for game_model.updator_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setUpdatorId(Long updatorId) {
        this.updatorId = updatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_model.update_time
     *
     * @return the value of game_model.update_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_model.update_time
     *
     * @param updateTime the value for game_model.update_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}