package com.artqiyi.dahuashai.game.domain;

import java.util.Date;

public class GameConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.game_model_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Long gameModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.game_model_key
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String gameModelKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.name
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.alias_name
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String aliasName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.type_key
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String typeKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.code
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.type_value
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String typeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.unit
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.sort
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.status
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.create_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.update_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.remark
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.create_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.update_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.id
     *
     * @return the value of game_config.id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.id
     *
     * @param id the value for game_config.id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.game_model_id
     *
     * @return the value of game_config.game_model_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Long getGameModelId() {
        return gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.game_model_id
     *
     * @param gameModelId the value for game_config.game_model_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setGameModelId(Long gameModelId) {
        this.gameModelId = gameModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.game_model_key
     *
     * @return the value of game_config.game_model_key
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getGameModelKey() {
        return gameModelKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.game_model_key
     *
     * @param gameModelKey the value for game_config.game_model_key
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setGameModelKey(String gameModelKey) {
        this.gameModelKey = gameModelKey == null ? null : gameModelKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.name
     *
     * @return the value of game_config.name
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.name
     *
     * @param name the value for game_config.name
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.alias_name
     *
     * @return the value of game_config.alias_name
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getAliasName() {
        return aliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.alias_name
     *
     * @param aliasName the value for game_config.alias_name
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setAliasName(String aliasName) {
        this.aliasName = aliasName == null ? null : aliasName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.type_key
     *
     * @return the value of game_config.type_key
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getTypeKey() {
        return typeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.type_key
     *
     * @param typeKey the value for game_config.type_key
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setTypeKey(String typeKey) {
        this.typeKey = typeKey == null ? null : typeKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.code
     *
     * @return the value of game_config.code
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.code
     *
     * @param code the value for game_config.code
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.type_value
     *
     * @return the value of game_config.type_value
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getTypeValue() {
        return typeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.type_value
     *
     * @param typeValue the value for game_config.type_value
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setTypeValue(String typeValue) {
        this.typeValue = typeValue == null ? null : typeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.unit
     *
     * @return the value of game_config.unit
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.unit
     *
     * @param unit the value for game_config.unit
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.sort
     *
     * @return the value of game_config.sort
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.sort
     *
     * @param sort the value for game_config.sort
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.status
     *
     * @return the value of game_config.status
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.status
     *
     * @param status the value for game_config.status
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.create_id
     *
     * @return the value of game_config.create_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.create_id
     *
     * @param createId the value for game_config.create_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.update_id
     *
     * @return the value of game_config.update_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.update_id
     *
     * @param updateId the value for game_config.update_id
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.remark
     *
     * @return the value of game_config.remark
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.remark
     *
     * @param remark the value for game_config.remark
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.create_time
     *
     * @return the value of game_config.create_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.create_time
     *
     * @param createTime the value for game_config.create_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.update_time
     *
     * @return the value of game_config.update_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.update_time
     *
     * @param updateTime the value for game_config.update_time
     *
     * @mbg.generated Tue Jul 03 17:01:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}